on: [push, pull_request]

name: CI

jobs:
  CI:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.19.0, 22, 24]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type checking
        if: ${{ !startsWith(github.head_ref || github.ref_name, 'javascript') }}
        run: npm run typecheck

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Validate Prisma
        run: npx prisma generate && npx prisma validate

      - name: Build application
        run: npm run build

      - name: Validate Shopify extensions
        run: npx shopify app build
